input:
  root: RootObject
  objects:
   RootObject:
    id: RootObject
    properties:
     toolset:
      type:
       type_id: string
     config:
       type:
         type_id: string
     relay:
       type:
         type_id: string
     server:
       type:
         type_id: string
     token:
       type:
         type_id: string

steps:
  startemup:
   plugin: localhost/parcaflow
   step: main
   input:
    toolset: !expr $.input.toolset
    config: !expr $.input.config
    server: !expr $.input.server
    relay: !expr $.input.relay
    token: !expr $.input.token

output:
  message: !expr $.steps.startemup.outputs.success.message
