name: Build
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Build image
        run: buildah build Containerfile.test
      - name: Run plugin
        run: podman pod up
      - name: Extract coverage data
        run: |
          podman create --name test quay.io/arcalot/parcaflow:latest
          podman cp test:/htmlcov .
          podman rm test
      - name: Publish coverage report to job summary
        run: |
          pip install html2text
          html2text --ignore-images --ignore-links -b 0 htmlcov/index.html >> $GITHUB_STEP_SUMMARY
      - name: Upload coverage results
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: htmlcov
          if-no-files-found: error
